### ISSUE TITLE
User Story 1:  User Registration

### ISSUE THREAD

**Issue by carlalennon** [carlalennon/animeasy-tools#1]
As a customer of the Animeasy, I want to be able to create an account where I can access information about my previous purchases and opt in to promotional emails and updates about projects, along with special offers. 

## Requirements:

- [x] Users can create a profile with animeasy
- [x] Users can log in and out of animeasy
- [x] The user's login status is reflected on screen at all times
- [x] User receives an email confirmation upon registration
- [x] Users can recover password if lost 

## Tasks: 

- [x] Install allauth to project 
- [x] Configure allauth within project 
- [x] Allow users to create an account using email address 
- [x] Create log in page for animeasy
- [x] Create register page for animeasy
- [x] Configure Welcome to Animeasy email to be sent upon registration
- [x] Create user password recovery page 
- [x] Users can recover password via an email link
