### ISSUE TITLE
User Story 11: Help and FAQs

### ISSUE THREAD

**Issue by carlalennon** [carlalennon/animeasy-tools#15]
AS a customer of Animeasy, I would like to be able to access an install guide for my new products 

## Acceptance Criteria: 
- [x] Add an install instructions page 
- [x] Add an FAQ page 

## Tasks: 
- [x] Create url for install instructions in home app
- [x] Create url for FAQ section in home app 
- [x] Create FAQ page 
- [x] Create install instructions page 
- [x] Link to Adobe scripting page in Install guide 
- [x] Link to TV Paint forums in install guide
