### ISSUE TITLE
User Story 2: Products

### ISSUE THREAD

**Issue by carlalennon** [carlalennon/animeasy-tools#2]
As a potential customer of Animeasy, I want to see what products are available to purchase

- [x] Users can view all products on Animeasy 
- [x] Users can filter products by category 
- [x] Users can search for products by key word 
- [x] Users can navigate to product detail page by clicking on search/filter results 

## Tasks: 

- [x] Create a page for all products on site
- [x] Create filter to sort products by category 
- [x] Create search function to return products by key word
- [x] Create filter to sort products by software 
- [x] User can sort by price ascending or descending
- [x] User can sort by SKU 
- [x] User can sort alphabetically 
- [x] User can sort by discount 
- [x] User can add to cart from search results
