### ISSUE TITLE
User Story 4: Navigation 

### ISSUE THREAD

**Issue by carlalennon** [carlalennon/animeasy-tools#3]
As a potential customer of Animeasy, I want to easily explore and find products on the site 

## Acceptance Criteria: 

- [x] Users can access the navigation bar from any page of the animeasy website 
- [x] The navigation bar contains a link to quickly browse all available products 
- [x] The nav bar features buttons to sort the product into software category

## Tasks: 

- [x] Implement a navigation bar across all pages of Animeasy
- [x] Follow wireframe to match design as close as possible, while adhering to UX principles

#### In Dark section:

- [x] "About" link that links to the About page
- [x] "Support" link that links to a contact form
- [x] "Cart" dropdown that allows users to see what's in their cart, if anything. Should include name, thumbnail and # items.
- [x] Cart dropdown also shows current price and link to checkout.
- [x] Link to Facebook page for Animeasy
- [x] Link to Linkedin page for Animeasy 
- [x] If User is admin, a link to Admin page for product managements
- [x] If User is logged in, a link to their profile page
- [x] If User is logged in, a link to Sign Out 
- [x] If User is logged out, a link to Sign In
- [x] If User is logged out, a link to Register 

#### In Light section: 

- [x] Animeasy logo, that's also a link to Home 
- [x] TV Paint section link
- [x] After Effects section link 
- [x] Big Red All Products button 

#### Mobile styling 

- [ ] In screens medium and below, collapse light section elements under burger menu 
- [ ] On smallest screens, collapse light and dark section elements into a burger element
