### ISSUE TITLE
User Story 5: User Profile

### ISSUE THREAD

**Issue by carlalennon** [carlalennon/animeasy-tools#5]
As a user, I can create a profile that allows me to purchase items easily 

## Acceptance Criteria: 

- [x] User is prompted to save details for next purchase 
- [x] User can change their profile data
- [x] User can see their order history

## Tasks: 

- [x] Create user account page where user can see their data
- [x] Users are identified by username and password 
- [x] Users can save their address
- [x] Users can save their card details 
- [x] Users can change their email and password 
- [x] Users can see a list of previous orders
- [x] Users can opt out of the newsletter
- [x] Users can opt into the newsletter
- [x] Users can contact customer support 

## Extras: 

![image](https://github.com/carlalennon/animeasy-tools/assets/99259113/668c1b70-142a-4798-9454-306257c2833f)
