### ISSUE TITLE
User Story 7: Admin Permissions

### ISSUE THREAD

**Issue by carlalennon** [carlalennon/animeasy-tools#7]
As a store owner, I can add, edit or delete products 

## Acceptance Criteria:

- [x] Only administrators can access these features
- [x] Products can be added to site
- [x] Products can be edited on the site 
- [x] Products can be deleted from site 

## Tasks: 

- [x] Create superuser to test permissions 
- [x] Add an edit button to pattern detail page that only appears if the viewer is logged in as a superuser/admin
- [x] Add a delete button to pattern detail page that only appears if the viewer is logged in as a superuser/admin
- [x] Add correct link to Admin in nav bar that brings user to Add a product page 
- [x] Add superuser lock to views to stop html editing allowing non-admin to see edit/delete pages 
- [x] Add edit/delete buttons to product cards in all products view
- [x] Add JS that prevents default on delete button, prompts the user with an alart to say "Are you sure?" and then deletes product is they agree, refresh if not
