### ISSUE TITLE
User Story 8: Newsletter

### ISSUE THREAD

**Issue by carlalennon** [carlalennon/animeasy-tools#8]
As a marketer of animeasy, I want to be able to reach out to my interested leads with offers and announcements of new products via email.

## Acceptance Criteria:
- [x] Admins can write newsletter on the front end 
- [x] Emails are sent from animeasytools@gmail.com
- [x] Users of the site can subscribe to emails 
- [x] Users of the site can unsubscribe from emails 
- [x] Emails are delivered to the inboxes of subscribers
 

## Tasks: 
- [x] In forms, check for duplicates and render form invalid if duplicates found
