### ISSUE TITLE
User Story 9: Contact Form 

### ISSUE THREAD

**Issue by carlalennon** [carlalennon/animeasy-tools#9]
As a seller, I would like a place to handle any issues from my customers 
As a customer, I would like a place to contact the seller should the need arise 

## Acceptance Criteria: 
- [x] User's can submit a ticket via the contact form 
- [x] Admins can see tickets 

## Tasks: 
- [x] Create contact app 
- [x] Hook up URL
- [x] Add url to header and footer 
- [x] Create a ticket form for customer 
- [x] Ensure only admins can access tickets view 
- [x] Admins can view all ticket 
- [x] Admins can open a ticket to see the content 
- [x] Tickets can be marked as "done"
- [x] Tickets can be sorted by "done" or "open"
## Extras: 
- [x] Admins can reply to the ticket using the frontend of the site 

Issue for tomrw: contact form in deploy is missing reply
